/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=AssistantEnv` (hash: 1436988cfc8a2ba7e7362483dc442576)
interface __BaseEnv_AssistantEnv {
	PER_IP: RateLimit;
	PER_ADMINISTRATIE: RateLimit;
	AI: Ai;
	ENABLED: string;
	GATEWAY_ID: string;
	MODEL: string;
	DAILY_QUOTA: string;
	TIMEOUT_MS: string;
	LICENTIE: Service /* entrypoint Controle from boekhoudenvoorniks-licentie */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_AssistantEnv {}
}
interface AssistantEnv extends __BaseEnv_AssistantEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENABLED" | "GATEWAY_ID" | "MODEL" | "DAILY_QUOTA" | "TIMEOUT_MS">> {}
}
